from pathlib import Path
import json,numpy as np,pandas as pd
ROOT=Path(__file__).resolve().parents[3];OUT=ROOT/'campaigns'/'CAM-0626'/'artifacts'/'RUN-0003';KEY=['symbol','target_ts','role']
def metrics(d):
 eq=1+d.net_pnl.cumsum();pk=np.maximum.accumulate(np.r_[1.,eq])[1:];mo=d.set_index('date').net_pnl.resample('ME').sum();wk=d.set_index('date').net_pnl.resample('W-FRI').sum();yr=d.groupby(d.date.dt.year).net_pnl.sum();return {'net_return':float(d.net_pnl.sum()),'max_drawdown':float(-(eq/pk-1).min()),'positive_days':int((d.net_pnl>0).sum()),'negative_days':int((d.net_pnl<0).sum()),'positive_weeks':int((wk>0).sum()),'negative_weeks':int((wk<0).sum()),'positive_months':int((mo>0).sum()),'negative_months':int((mo<0).sum()),'worst_day':float(d.net_pnl.min()),'worst_month':float(mo.min()),'worst_year':float(yr.min())}
def main():
 e=pd.read_parquet(OUT/'entry_package_audit.parquet');e=e[e.package_executable].copy();e.date=pd.to_datetime(e.date);m=pd.read_parquet(OUT/'minute_stop_ledger.parquet');m.date=pd.to_datetime(m.date);m.exit_target_ts=pd.to_datetime(m.exit_target_ts,utc=True);q=pd.concat([pd.read_parquet(p) for p in OUT.glob('quotes_exit_minute*60s.parquet')],ignore_index=True);q.target_ts=pd.to_datetime(q.target_ts,utc=True);q.quote_ts=pd.to_datetime(q.quote_ts,utc=True);q['delay_seconds']=(q.quote_ts-q.target_ts).dt.total_seconds();q=q[(q.delay_seconds>=0)&(q.delay_seconds<=60)].sort_values(['delay_seconds','quote_ts']).drop_duplicates(KEY)
 z=m.merge(q,left_on=['symbol','exit_target_ts','exit_role'],right_on=KEY,how='left',validate='one_to_one');z['exit_fill']=np.where(z.exit_side.eq('buy'),z.ask_price,z.bid_price);z['complete']=z.exit_fill.notna();z['quote_gross_pnl']=np.where(z.position_side.eq('long'),z.weight*(z.exit_fill/z.entry_fill-1),z.weight*(1-z.exit_fill/z.entry_fill))
 all_days=pd.DataFrame({'date':pd.date_range('2024-05-01','2026-04-30',freq='B')});actual=pd.DataFrame({'date':pd.to_datetime(pd.read_parquet(OUT/'bar_daily.parquet').date.unique())});all_days=actual.sort_values('date');rows=[]
 for b in (0,1,2,5,10):
  t=z[z.complete].copy();t['net_pnl']=t.quote_gross_pnl-t.weight*2*b/10000;d=t.groupby('date').agg(net_pnl=('net_pnl','sum'),gross_pnl=('quote_gross_pnl','sum'),gross=('weight','sum'),legs=('symbol','size')).reset_index();d=all_days.merge(d,on='date',how='left').fillna(0);mm=metrics(d);mm.update({'additional_bps_per_side':b,'gross_return':float(d.gross_pnl.sum()),'complete_trade_coverage':float(z.complete.mean()),'executed_package_days':int((d.gross>0).sum())});rows.append(mm);d.to_parquet(OUT/f'minute_quote_daily_{b}bps.parquet',index=False)
 z.to_parquet(OUT/'minute_quote_trades.parquet',index=False);missing=z[~z.complete];missing.to_parquet(OUT/'minute_missing_exits.parquet',index=False);report={'status':'completed' if z.complete.all() else 'incomplete_blocked','execution_model':'actual marketable entry; raw SIP 1m first stop crossing; first marketable exit quote after minute completion; whole package cancelled on any missing entry','intended_package_days':int(pd.read_parquet(OUT/'entry_package_audit.parquet').date.nunique()),'executed_package_days':int(m.date.nunique()),'cancelled_package_days':int(pd.read_parquet(OUT/'entry_package_audit.parquet').date.nunique()-m.date.nunique()),'exit_role_coverage':float(z.complete.mean()),'missing_exits':len(missing),'maximum_loaded_date':str(m.date.max().date()),'holdout_rows_loaded':0,'metrics':rows};(OUT/'minute_quote_report.json').write_text(json.dumps(report,indent=2)+'\n');print(pd.DataFrame(rows).to_string(index=False));print({k:report[k] for k in ('status','intended_package_days','executed_package_days','cancelled_package_days','exit_role_coverage','missing_exits')})
if __name__=='__main__':main()
