from pathlib import Path
import json,numpy as np,pandas as pd
ROOT=Path(__file__).resolve().parents[3];OUT=ROOT/'campaigns'/'CAM-0626'/'artifacts'/'RUN-0009';SRC=ROOT/'campaigns'/'CAM-0626'/'artifacts'/'RUN-0007';OUT.mkdir(parents=True,exist_ok=True);KEY=['symbol','target_ts','role']
def prepare():
 t=pd.read_parquet(SRC/'best_trades.parquet');t.date=pd.to_datetime(t.date);rows=[]
 for x in t.itertuples():
  for phase,clock,side in [('entry',x.entry_time,'buy' if x.side=='long' else 'sell'),('exit',x.exit_time,'sell' if x.side=='long' else 'buy')]:
   ts=pd.to_datetime(pd.Timestamp(x.date).strftime('%Y-%m-%d')+' '+clock).tz_localize('America/New_York').tz_convert('UTC');rows.append({'date':x.date,'symbol':x.symbol,'position_side':x.side,'weight':x.weight,'phase':phase,'order_side':side,'target_ts':ts,'role':f'{phase}_sector_{"ask" if side=="buy" else "bid"}_after'})
 l=pd.DataFrame(rows);l.to_parquet(OUT/'ledger.parquet',index=False);l[KEY].drop_duplicates().to_parquet(OUT/'roles.parquet',index=False);print({'trades':len(t),'roles':len(l),'days':int(t.date.nunique()),'max_date':str(t.date.max().date())})
def replay():
 l=pd.read_parquet(OUT/'ledger.parquet');l.date=pd.to_datetime(l.date);l.target_ts=pd.to_datetime(l.target_ts,utc=True);parts=[pd.read_parquet(p) for p in OUT.glob('quotes*.parquet')];q=pd.concat(parts,ignore_index=True);q.target_ts=pd.to_datetime(q.target_ts,utc=True);q.quote_ts=pd.to_datetime(q.quote_ts,utc=True);q['delay']=(q.quote_ts-q.target_ts).dt.total_seconds();q=q[(q.delay>=0)&(q.delay<=60)].sort_values(['delay','quote_ts']).drop_duplicates(KEY);z=l.merge(q,on=KEY,how='left',validate='one_to_one');z['fill']=np.where(z.order_side.eq('buy'),z.ask_price,z.bid_price);w=z.pivot(index=['date','symbol','position_side','weight'],columns='phase',values='fill').reset_index();w['complete']=w.entry.notna()&w.exit.notna();w['day_ok']=w.groupby('date').complete.transform('all');w['gross_pnl']=np.where(w.position_side.eq('long'),w.weight*(w.exit/w.entry-1),w.weight*(1-w.exit/w.entry));days=pd.DataFrame({'date':sorted(l.date.unique())});rows=[]
 for b in (0,1,2,5,10):
  x=w[w.day_ok].copy();x['net_pnl']=x.gross_pnl-x.weight*2*b/10000;d=x.groupby('date').agg(net_pnl=('net_pnl','sum'),gross=('weight','sum')).reset_index();d=days.merge(d,on='date',how='left').fillna(0);eq=1+d.net_pnl.cumsum();pk=np.maximum.accumulate(np.r_[1.,eq])[1:];mo=d.set_index('date').net_pnl.resample('ME').sum();wk=d.set_index('date').net_pnl.resample('W-FRI').sum();rows.append({'additional_bps_per_side':b,'net_return':float(d.net_pnl.sum()),'max_drawdown':float(-(eq/pk-1).min()),'positive_days':int((d.net_pnl>0).sum()),'negative_days':int((d.net_pnl<0).sum()),'positive_weeks':int((wk>0).sum()),'negative_weeks':int((wk<0).sum()),'positive_months':int((mo>0).sum()),'negative_months':int((mo<0).sum()),'worst_month':float(mo.min()),'executed_days':int((d.gross>0).sum())});d.to_parquet(OUT/f'daily_{b}bps.parquet',index=False)
 report={'status':'completed' if w.complete.all() else 'incomplete_blocked','role_coverage':float(z['fill'].notna().mean()),'complete_trade_coverage':float(w.complete.mean()),'metrics':rows,'maximum_loaded_date':str(l.date.max().date()),'holdout_rows_loaded':0};(OUT/'report.json').write_text(json.dumps(report,indent=2)+'\n');w.to_parquet(OUT/'trades.parquet',index=False);print(pd.DataFrame(rows).to_string(index=False));print(report['status'])
if __name__=='__main__':prepare()
